### ISSUE TITLE
I found an error when purchasing

### ISSUE THREAD

**Issue by cerorar** [wrteam-jay/Elite-Quiz-Issues-Tracker#19]
I found an error when purchasing through the android playstore. And the user buys coins and makes a refund there is no way to know who the user was who requested the refund in the playstore. This means that you have access to purchases for free, which is a failure. A user identification could be implemented through the exact date and time that the purchase was made and see in the developer console in payments which purchase was reimbursed and coincides with the time. But in the activities track menu only the date appears but not the time, it is difficult to know if two users buy on the same day https://ibb.co/RYGYNrs

That the ID of the order is stored in a database for consultation and to identify the user who commits fraud

https://ibb.co/Qk7T9VP

**Comment by wrteam-jay** [comment]
Hi @cerorar, Thank you for your feedback. we have added the functionality to map the transactions with the play store/app store in the admin panel.

it will be available with next update (v2.1.9).

Thank you.
