### ISSUE TITLE
Overflow on Contest (home page)

### ISSUE THREAD

**Issue by Joan1211** [wrteam-jay/Elite-Quiz-Issues-Tracker#5]
**Describe the bug**
In the home page, if we choose a too long title for the contest, there is an overflow.

![Simulator Screenshot - iPhone 15 Pro - 2024-05-06 at 08 48 34](https://github.com/wrteam-jay/Elite-Quiz-Issues-Tracker/assets/59017905/b301939d-e112-40e7-8937-353c38b27ffb)

**Comment by wrteam-jay** [comment]
Thanks for reporting the issue, it has been fixed and fix will be available in the next update.
