### ISSUE TITLE
Upcoming contest not published

### ISSUE THREAD

**Issue by Joan1211** [wrteam-jay/Elite-Quiz-Issues-Tracker#8]
If the upcoming contest is scheduled for today (the same day it is set up) and occurs in a few hours, it will not be listed as upcoming. 

Upcoming contests are only displayed if they are scheduled for the next day.

**Comment by wrteam-jay** [comment]
Hi @Joan1211, Thank you for your feedback it has been fixed, and fix will be available in next update (v2.1.9).
